mqtt:
  hostname: 127.0.0.1       # MQTT broker address (required)
  port: 1883                # MQTT broker port (defaults to 1883)
  user: username            # Username for MQTT credentials (required)
  password: secret          # Username for MQTT credentials (required)
  connection_retry: 10      # Seconds between reconnection attempts if disconnected (default 10)
deviceName: Example Client  # Pretty/display name sent with this MQTT topic (required)
client_id: example_client   # Client ID/name of this device for the MQTT broker (required)
timezone: Europe/Brussels   # The system's local timezone (required)
update_interval: 60         # Seconds between updating sensor values and publishing to broker (default 60)
sensors:
  hardware_make: true
  hardware_model: true
  temperature: true
  clock_speed: true
  cpu_model: false
  cpu_usage: true
  load_1m: true
  load_5m: true
  load_15m: true
  memory_use: true
  swap_usage: true
  hostname: true
  host_ip: true
  host_os: true
  host_arch: true
  updates: true
  wifi_strength: true
  wifi_ssid: true
  net_tx: true
  net_rx: true
  last_boot: true
  last_message: true
  power_status: true
  disk_use: true
  external_drives: # Only add mounted drives here, e.g.:
    # Drive1: /media/storage